# Ansible inventory created from ['/home/ravi/NetworkAutomation/netlab-again/sample-topology.yaml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
box: ceos:4.32.1F
clab:
  env:
    CLAB_MGMT_VRF: management
    INTFTYPE: et
  kind: ceos
hostname: clab-netlab_again-e1
interfaces:
- clab:
    name: et1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.18/30
  linkindex: 5
  name: e1 -> c1
  neighbors:
  - ifname: Ethernet1
    ipv4: 10.1.0.17/30
    node: c1
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  type: p2p
- clab:
    name: et2
  ifindex: 2
  ifname: Ethernet2
  ipv4: 10.1.0.22/30
  linkindex: 6
  name: e1 -> c2
  neighbors:
  - ifname: Ethernet1
    ipv4: 10.1.0.21/30
    node: c2
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  type: p2p
loopback:
  ifindex: 0
  ifname: Loopback0
  ipv4: 10.0.0.5/32
  neighbors: []
  ospf:
    area: 0.0.0.0
  type: loopback
  virtual_interface: true
mgmt:
  ifname: Management0
  ipv4: 192.168.121.105
  mac: 08:4f:a9:00:00:05
module:
- ospf
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.5
