# Ansible inventory created from ['/home/ravi/NetworkAutomation/netlab-again/sample-topology.yaml', 'package:topology-defaults.yml']
#

af: {}
box: python:3.9-alpine
clab:
  binds:
  - clab_files/H3/hosts:/etc/hosts
  config_templates:
  - hosts:/etc/hosts
  kind: linux
hostname: clab-netlab_again-H3
interfaces: []
mgmt:
  ifname: eth0
  ipv4: 192.168.121.112
  mac: 08:4f:a9:00:00:0c
mtu: 1500
role: host
