# Ansible inventory created from ['/home/ravi/NetworkAutomation/netlab-again/DC-Leaf-Spine-Topology.yaml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
interfaces:
- ipv4: 10.1.0.9/30
  type: p2p
  linkindex: 3
  name: L2 -> S1
  ifindex: 1
  ifname: Ethernet1
  clab:
    name: et1
  neighbors:
  - ifname: Ethernet2
    node: S1
    ipv4: 10.1.0.10/30
  ospf:
    area: 0.0.0.0
    passive: false
    network_type: point-to-point
- ipv4: 10.1.0.13/30
  type: p2p
  linkindex: 4
  name: L2 -> S2
  ifindex: 2
  ifname: Ethernet2
  clab:
    name: et2
  neighbors:
  - ifname: Ethernet2
    node: S2
    ipv4: 10.1.0.14/30
  ospf:
    area: 0.0.0.0
    passive: false
    network_type: point-to-point
_fabric_count: 2
module:
- vlan
- bgp
- ospf
- evpn
clab:
  kind: ceos
  env:
    INTFTYPE: et
    CLAB_MGMT_VRF: management
box: ceos:4.32.1F
ospf:
  area: 0.0.0.0
  router_id: 10.0.0.2
  af:
    ipv4: true
bgp:
  advertise_loopback: true
  community:
    ibgp:
    - standard
    - large
    - extended
    ebgp:
    - standard
    - large
    ibgp_localas:
    - standard
    - large
    - extended
  next_hop_self: true
  _cprop_order:
  - standard
  - extended
  - large
  - link-bandwidth
  as: 65000
  router_id: 10.0.0.2
  neighbors:
  - rr: true
    name: S1
    as: 65000
    type: ibgp
    ipv4: 10.0.0.4
    _source_ifname: Loopback0
    activate:
      ipv4: true
    evpn: true
  - rr: true
    name: S2
    as: 65000
    type: ibgp
    ipv4: 10.0.0.5
    _source_ifname: Loopback0
    activate:
      ipv4: true
    evpn: true
  ipv4: true
evpn:
  session:
  - ibgp
af:
  ipv4: true
loopback:
  type: loopback
  neighbors: []
  virtual_interface: true
  ipv4: 10.0.0.2/32
  ifname: Loopback0
  ifindex: 0
  ospf:
    area: 0.0.0.0
mgmt:
  ifname: Management0
  ipv4: 192.168.121.102
  mac: 08:4f:a9:00:00:02
hostname: clab-netlab_again-L2
