# Ansible inventory created from ['/home/ravi/NetworkAutomation/netlab-again/DC-Leaf-Spine-Topology.yaml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
ansible_user: admin
ansible_ssh_pass: admin
ansible_network_os: eos
ansible_connection: network_cli
ansible_become: 'yes'
ansible_become_method: enable
