# Ansible inventory created from ['/home/ravi/NetworkAutomation/netlab-again/DC-Leaf-Spine-Topology.yaml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
interfaces: []
clab:
  kind: linux
  config_templates:
  - hosts:/etc/hosts
  binds:
  - clab_files/H2/hosts:/etc/hosts
box: python:3.9-alpine
role: host
mtu: 1500
af: {}
mgmt:
  ifname: eth0
  ipv4: 192.168.121.107
  mac: 08:4f:a9:00:00:07
hostname: clab-netlab_again-H2
